# 変数の型
以下は変数a,bそれぞれに数値、文字列を出力するコーディングである。

In [1]:
a=123
print(a)
b='今日は晴れ'
print(b)

111
今日は晴れ


上記のbについて1文字目を取り出すには以下のようにコーディングする。

In [2]:
c = b[0]
print(c)

今


1. 上記のbから'晴'の1文字を取り出せ
2. 上記のaから1だけを取り出すにはどうしたらよいか

晴
1


1. 以下のa, bを演算子を使って'今日は晴れ'という文字列を表示せよ
2. 次に、1.と同様に演算子を使って'今日は5月22日' という文字列を変数 c,d,e,f,gから作成して表示せよ
3. .format()を使って、'今日は5月22日'　の5,22を整数値のままで表示せよ

In [10]:
a='今日は'
b='晴れ'


c = '今日は'
d = 5
e = '月'
f = 22
g = '日'





今日は晴れ
今日は5月22日
今日は5月22日


# 配列
1. 以下のリスト型から、'バター'を取り出せ
2. 次に、バターから小麦粉までの部分配列を取り出せ


In [5]:
recipe = ['チョコレート','バター', '卵', '砂糖', '小麦粉', '好きジャム']


バター
['バター', '卵', '砂糖', '小麦粉']


1. 以下の2次元配列リスト型から、2行目の配列を取り出せ
2. 次に、2行目のチョコ、バターだけを取り出せ
3. 同様に、4行目のイチゴを取り出し、更にイチゴのチを取り出せ

In [6]:
recipes = [['チョコレート','バター', '卵', '砂糖', '小麦粉', '好きジャム'],
['生クリーム', 'チョコ', 'バター', '砂糖', '卵', '小麦粉'],
['卵', 'グラニュー', 'チョコレート', '食塩', '小麦粉', '卵白'],
['フォンダンショコラ', 'アイスクリーム', 'イチゴ', 'コイン'],
['チョコレート', '卵', '砂糖', '小麦粉', 'バター', '生地']]

['生クリーム', 'チョコ', 'バター', '砂糖', '卵', '小麦粉']
['チョコ', 'バター']
イチゴ
チ


'2'

上記recipesに以下の1行を加えよ

In [7]:
l=['チョコ', 'バター', 'ココア']

In [8]:
recipes.append(l)
recipes

[['チョコレート', 'バター', '卵', '砂糖', '小麦粉', '好きジャム'],
 ['生クリーム', 'チョコ', 'バター', '砂糖', '卵', '小麦粉'],
 ['卵', 'グラニュー', 'チョコレート', '食塩', '小麦粉', '卵白'],
 ['フォンダンショコラ', 'アイスクリーム', 'イチゴ', 'コイン'],
 ['チョコレート', '卵', '砂糖', '小麦粉', 'バター', '生地'],
 ['チョコ', 'バター', 'ココア']]

In [4]:
list=['a','b']
list.append('c')
list

['a', 'b', 'c']

In [ ]:
以下のリスト要素をつなげて１つの文字列にせよ

In [27]:
k = ['今日','の','天気','は','晴れ']

今日の天気は晴れ


# numpy 配列
1. 以下の数値のリストから5を取り出せ
2. 5～8を取り出せ
3. 以下のリスト型をnumpy型に変換して上記1,2と同じ処理を行え
4. 以下のリスト型について、要素を1つ1つ書きこまずにnumpy配列として作成せよ

In [53]:
a = [0,1,2,3,4,5,6,7,8,9,10,11]


In [11]:
import numpy as np
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
1. 以下の配列から2行目の5.6を取り出せ
2. 以下の配列をnumpy型に変換して、1.と同じ処理を行え 
3. 変換した配列から、5,6,9,10を行列の形式で取り出せ

In [40]:
c = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]

In [ ]:
c[1:3,1:3]

[5, 6]
[5 6]
[[ 5  6]
 [ 9 10]]


In [ ]:
以下の1次元配列を上記cと同じ2次元配列にnumpyのメソッドを使って変換せよ


In [14]:
e = np.array([0,1,2,3,4,5,6,7,8,9,10,11])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
同様にして以下のような3次元配列に変換せよ

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
1. 上記3次元配列から2つ目の行列中の9を取り出せ
2. 同様に1つ目の行列中の2 3を取り出せ

9
[2 3]


# 連結
1. 1次元配列 gを、2次元配列（行列）eの最下行に追加せよ
2. 1次元配列 hを、eの左に１列追加せよ  
ヒント：np.concatenateを使う

In [21]:
import numpy as np
e=np.arange(12).reshape(3,4)
g=np.array([1,2,3,4])
h=np.array([1,2,3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  2  3  4]]
[[ 0  1  2  3  1]
 [ 4  5  6  7  2]
 [ 8  9 10 11  3]]


# インデックスの取得
1. 上記の2次元配列 e について行毎に最大値を取り出せ
2. 同様にして行毎に最大値のインデックス（列番号）を取り出せ
3. e について列毎に最大値を取り出せ
4. 同様にして列毎に最大値のインデックス（行番号）を取り出せ
5. e について3の倍数だけを取り出せ
6. e について3の倍数のインデックスを取り出せ


[ 3  7 11]
[3 3 3]
[ 8  9 10 11]
[2 2 2 2]
[0 3 6 9]
(array([0, 0, 1, 2], dtype=int64), array([0, 3, 2, 1], dtype=int64))


# 行列の積
1. ベクトル g と行列 e の積を計算せよ
2. 行列 e とベクトル h.T の積を計算せよ(.Tは転置)
3. g・e・h.T を計算せよ

In [27]:
e=np.arange(12).reshape(4,3)
print(e)
g=np.array([1,2,3,4])
h=np.array([1,2,3])



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[60 70 80]
[[ 8]
 [26]
 [44]
 [62]]
[440]
